clone_depth: 1
image: Visual Studio 2017
platform: x64
configuration: Release

install:
    - cd C:\projects
    - git clone -q --depth 1 https://github.com/pioneerspacesim/pioneer-thirdparty.git
    - cd C:\projects\pioneer-thirdparty\win32\lib\x64\vs2017
    - rename freetype271MT.lib freetype.lib

build_script:
    - cd C:\projects\pioneer

    - cmake -DCMAKE_BUILD_TYPE:STRING=Release .
    - cmake --build . --config Release
